# Generated by Django 3.2.4 on 2021-06-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('heading', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_title', models.CharField(blank=True, max_length=255, null=True)),
                ('button_text', models.CharField(blank=True, max_length=255, null=True)),
                ('button_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ('cdate',),
                'abstract': False,
            },
        ),
    ]
