# Generated by Django 3.2.4 on 2021-06-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_slider_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('heading', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('percent_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('percent', models.IntegerField()),
                ('order', models.IntegerField(default=999)),
            ],
            options={
                'ordering': ('cdate',),
                'abstract': False,
            },
        ),
    ]
