# Generated by Django 3.2.4 on 2021-06-16 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads'),
        ),
    ]
