# Generated by Django 3.2.4 on 2021-06-14 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='chk',
            field=models.BooleanField(default=False),
        ),
    ]
